---

# the 3 dashes bellow indicates that this is a yml document, if there are more dashes bellow it will indicate new yml documents
name: Checks

# On github push do these jobs
on: [push]

jobs:

  # Do tests and linting in the docker image saved to docker hub
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # This image already have docker and docker compose
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Login with docker action
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout # Code checkout to be used in the next steps
        uses: actions/checkout@v2 

      - name: Test  # Test step
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint # Lint step
        run: docker-compose run --rm app sh -c "flake8"